-- NOTE: ALTER TYPE ... ADD VALUE cannot run inside a transaction block.
-- Supabase runs each migration file in a transaction by default, so these
-- statements are placed first and use IF NOT EXISTS to be idempotent.
ALTER TYPE plan_tier ADD VALUE IF NOT EXISTS 'mystery_s';
ALTER TYPE plan_tier ADD VALUE IF NOT EXISTS 'mystery_m';

-- Add new columns to plans table
ALTER TABLE plans
  ADD COLUMN IF NOT EXISTS name          text,
  ADD COLUMN IF NOT EXISTS tagline       text,
  ADD COLUMN IF NOT EXISTS annual_price  numeric(10,2),
  ADD COLUMN IF NOT EXISTS perks         jsonb NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS comparison_data jsonb NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS featured      boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS active        boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sort_order    integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS accent_color  text NOT NULL DEFAULT '#F5F1EB',
  ADD COLUMN IF NOT EXISTS cta_bg        text NOT NULL DEFAULT '#F5F1EB',
  ADD COLUMN IF NOT EXISTS cta_text      text NOT NULL DEFAULT '#001B21',
  ADD COLUMN IF NOT EXISTS brick_image   text,
  ADD COLUMN IF NOT EXISTS cta_label     text;

-- Upsert all 6 plans
INSERT INTO plans (id, name, tagline, price, annual_price, bg_color, text_color, accent_color, cta_bg, cta_text, brick_image, cta_label, sort_order, featured, active, level, perks, comparison_data) VALUES

('mystery_s',
 'Mystery Box Mėgėjams',
 NULL,
 19.99,
 15.99,
 '#1C1C2E',
 '#F5F1EB',
 '#F5F1EB',
 '#F5F1EB',
 '#001B21',
 '/plans/starter.svg',
 'Pradėti su Mystery S',
 1,
 false,
 true,
 1,
 '[{"label":"1 S dydžio rinkinys per mėnesį","included":true},{"label":"Iki 800 kaladėlių","included":true},{"label":"Rinkinys parenkamas automatiškai","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Nemokamas pristatymas paštomatu","included":true},{"label":"Pats renkiesi rinkinį","included":false},{"label":"Ankstyva prieiga prie naujų rinkinių","included":false}]',
 '{"Rinkiniai per mėnesį":"1× S","Maks. kaladėlių":"800","Briksių kreditai":"—","Rinkinį renkiesi pats":"—","Fizinė instrukcija":"✓","Ankstyva prieiga":"—","Pristatymas":"Paštomatas","Grąžinimo terminas":"Neribotas"}'
),

('nano',
 'Mėgėjas',
 'Pirmas žingsnis į kolekciją.',
 24.99,
 19.99,
 '#FB4903',
 '#F5F1EB',
 '#F5F1EB',
 '#F5F1EB',
 '#001B21',
 '/plans/starter.svg',
 'Pradėti su Mėgėju',
 2,
 false,
 true,
 2,
 '[{"label":"1 S dydžio rinkinys per mėnesį","included":true},{"label":"Iki 800 kaladėlių","included":true},{"label":"100 Briksių kreditų","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Nemokamas pristatymas paštomatu","included":true},{"label":"Ankstyva prieiga prie naujų rinkinių","included":false},{"label":"Nemokamas pristatymas kurjeriu","included":false}]',
 '{"Rinkiniai per mėnesį":"1× S","Maks. kaladėlių":"800","Briksių kreditai":"100","Rinkinį renkiesi pats":"✓","Fizinė instrukcija":"✓","Ankstyva prieiga":"—","Pristatymas":"Paštomatas","Grąžinimo terminas":"Neribotas"}'
),

('mystery_m',
 'Mystery Box Kūrėjams',
 NULL,
 29.99,
 23.99,
 '#2D1B69',
 '#F5F1EB',
 '#F5F1EB',
 '#F5F1EB',
 '#001B21',
 '/plans/advanced.svg',
 'Pradėti su Mystery M',
 3,
 false,
 true,
 3,
 '[{"label":"1 M dydžio rinkinys per mėnesį","included":true},{"label":"Iki 2 000 kaladėlių","included":true},{"label":"Rinkinys parenkamas automatiškai","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Nemokamas pristatymas paštomatu","included":true},{"label":"Pats renkiesi rinkinį","included":false},{"label":"Ankstyva prieiga prie naujų rinkinių","included":false}]',
 '{"Rinkiniai per mėnesį":"1× M","Maks. kaladėlių":"2 000","Briksių kreditai":"—","Rinkinį renkiesi pats":"—","Fizinė instrukcija":"✓","Ankstyva prieiga":"—","Pristatymas":"Paštomatas","Grąžinimo terminas":"Neribotas"}'
),

('mini',
 'Kūrėjas',
 'Daugiau erdvės kūrybai.',
 34.99,
 27.99,
 '#5C4ADE',
 '#F5F1EB',
 '#F5F1EB',
 '#F5F1EB',
 '#001B21',
 '/plans/advanced.svg',
 'Pradėti su Kūrėju',
 4,
 true,
 true,
 4,
 '[{"label":"1 M arba 2× S dydžio rinkiniai","included":true},{"label":"Iki 2 000 kaladėlių","included":true},{"label":"200 Briksių kreditų","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Nemokamas pristatymas paštomatu","included":true},{"label":"Ankstyva prieiga prie naujų rinkinių","included":false},{"label":"Nemokamas pristatymas kurjeriu","included":false}]',
 '{"Rinkiniai per mėnesį":"1× M arba 2× S","Maks. kaladėlių":"2 000","Briksių kreditai":"200","Rinkinį renkiesi pats":"✓","Fizinė instrukcija":"✓","Ankstyva prieiga":"—","Pristatymas":"Paštomatas","Grąžinimo terminas":"Neribotas"}'
),

('standard',
 'Meistras',
 'Rimtiems statytojams.',
 49.99,
 39.99,
 '#55DB9C',
 '#001B21',
 '#001B21',
 '#001B21',
 '#F5F1EB',
 '/plans/builder.svg',
 'Pradėti su Meistru',
 5,
 false,
 true,
 5,
 '[{"label":"1 L, 2 M arba iki 3 S dydžio rinkiniai","included":true},{"label":"Iki 4 400 kaladėlių","included":true},{"label":"300 Briksių kreditų","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Ankstyva prieiga prie naujų rinkinių","included":true},{"label":"Nemokamas pristatymas paštomatu","included":true},{"label":"Nemokamas pristatymas kurjeriu","included":false}]',
 '{"Rinkiniai per mėnesį":"1× L, 2× M arba iki 3× S","Maks. kaladėlių":"4 400","Briksių kreditai":"300","Rinkinį renkiesi pats":"✓","Fizinė instrukcija":"✓","Ankstyva prieiga":"✓","Pristatymas":"Paštomatas","Grąžinimo terminas":"Neribotas"}'
),

('mega',
 'Legenda',
 'Visa LEGO visata.',
 79.99,
 63.99,
 '#4DA2FF',
 '#001B21',
 '#001B21',
 '#001B21',
 '#F5F1EB',
 '/plans/legend.svg',
 'Pradėti su Legenda',
 6,
 false,
 true,
 6,
 '[{"label":"1 Premium arba įvairūs deriniai (iki 4× S)","included":true},{"label":"Iki 11 000 kaladėlių","included":true},{"label":"400 Briksių kreditų","included":true},{"label":"Fizinė instrukcija","included":true},{"label":"Ankstyva prieiga prie naujų rinkinių","included":true},{"label":"Nemokamas pristatymas kurjeriu","included":true}]',
 '{"Rinkiniai per mėnesį":"1× Premium arba iki 4× S","Maks. kaladėlių":"11 000","Briksių kreditai":"400","Rinkinį renkiesi pats":"✓","Fizinė instrukcija":"✓","Ankstyva prieiga":"✓","Pristatymas":"Kurjeris","Grąžinimo terminas":"Neribotas"}'
)

ON CONFLICT (id) DO UPDATE SET
  name             = EXCLUDED.name,
  tagline          = EXCLUDED.tagline,
  price            = EXCLUDED.price,
  annual_price     = EXCLUDED.annual_price,
  bg_color         = EXCLUDED.bg_color,
  text_color       = EXCLUDED.text_color,
  accent_color     = EXCLUDED.accent_color,
  cta_bg           = EXCLUDED.cta_bg,
  cta_text         = EXCLUDED.cta_text,
  brick_image      = EXCLUDED.brick_image,
  cta_label        = EXCLUDED.cta_label,
  sort_order       = EXCLUDED.sort_order,
  featured         = EXCLUDED.featured,
  active           = EXCLUDED.active,
  level            = EXCLUDED.level,
  perks            = EXCLUDED.perks,
  comparison_data  = EXCLUDED.comparison_data;
