-- Merge overlapping permissive RLS policies (advisor: multiple_permissive_policies).
-- Each table/role/action now has a single policy, with admin access folded in via
-- OR. Semantics are unchanged:
--   * "FOR ALL" admin policies become INSERT/UPDATE/DELETE (SELECT is covered by
--     the public read policy, or merged into the read policy below).
--   * Dead policies are dropped: gift_cards "Service role insert/update" (always
--     false) and subscriber_penalties "service role all" (service_role bypasses RLS).
-- Rollback: re-create the dropped policies from the earlier migrations.

drop policy if exists "achievements_admin_write" on public.achievements;
create policy "achievements_admin_insert" on public.achievements for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "achievements_admin_update" on public.achievements for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "achievements_admin_delete" on public.achievements for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "coupons_admin_write" on public.coupons;
create policy "coupons_admin_insert" on public.coupons for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "coupons_admin_update" on public.coupons for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "coupons_admin_delete" on public.coupons for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "faq_items_admin_write" on public.faq_items;
create policy "faq_items_admin_insert" on public.faq_items for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "faq_items_admin_update" on public.faq_items for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "faq_items_admin_delete" on public.faq_items for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "home_content_admin_write" on public.home_content;
create policy "home_content_admin_insert" on public.home_content for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_content_admin_update" on public.home_content for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_content_admin_delete" on public.home_content for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "home_how_it_works_steps_admin_write" on public.home_how_it_works_steps;
create policy "home_how_it_works_steps_admin_insert" on public.home_how_it_works_steps for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_how_it_works_steps_admin_update" on public.home_how_it_works_steps for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_how_it_works_steps_admin_delete" on public.home_how_it_works_steps for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "home_marquee_items_admin_write" on public.home_marquee_items;
create policy "home_marquee_items_admin_insert" on public.home_marquee_items for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_marquee_items_admin_update" on public.home_marquee_items for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_marquee_items_admin_delete" on public.home_marquee_items for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "home_testimonials_admin_write" on public.home_testimonials;
create policy "home_testimonials_admin_insert" on public.home_testimonials for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_testimonials_admin_update" on public.home_testimonials for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "home_testimonials_admin_delete" on public.home_testimonials for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "page_headers_admin_write" on public.page_headers;
create policy "page_headers_admin_insert" on public.page_headers for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "page_headers_admin_update" on public.page_headers for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "page_headers_admin_delete" on public.page_headers for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "plans_admin_write" on public.plans;
create policy "plans_admin_insert" on public.plans for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "plans_admin_update" on public.plans for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "plans_admin_delete" on public.plans for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "products_admin_write" on public.products;
create policy "products_admin_insert" on public.products for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "products_admin_update" on public.products for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "products_admin_delete" on public.products for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "product_categories_admin_all" on public.product_categories;
create policy "product_categories_admin_insert" on public.product_categories for insert to authenticated with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "product_categories_admin_update" on public.product_categories for update to authenticated using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "product_categories_admin_delete" on public.product_categories for delete to authenticated using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "gift_cards_admin_write" on public.gift_cards;
create policy "gift_cards_admin_insert" on public.gift_cards for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "gift_cards_admin_update" on public.gift_cards for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "gift_cards_admin_delete" on public.gift_cards for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "Service role insert" on public.gift_cards;
drop policy if exists "Service role update" on public.gift_cards;
drop policy if exists "merch_admin_read" on public.merch_items;
drop policy if exists "merch_public_read" on public.merch_items;
create policy "merch_read" on public.merch_items for select using ((status = any (array['active'::text, 'coming-soon'::text])) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "feed_items_select_anon" on public.feed_items;
drop policy if exists "feed_items_select_auth" on public.feed_items;
create policy "feed_items_select" on public.feed_items for select using (((status = 'approved'::text) and (not is_hidden)) or (subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "feed_items_admin_delete" on public.feed_items;
drop policy if exists "feed_items_delete_own" on public.feed_items;
create policy "feed_items_delete" on public.feed_items for delete using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "feed_likes_select_auth" on public.feed_likes;
drop policy if exists "product_reviews_admin_all" on public.product_reviews;
drop policy if exists "product_reviews_public_read" on public.product_reviews;
drop policy if exists "product_reviews_select_own" on public.product_reviews;
drop policy if exists "product_reviews_insert_own" on public.product_reviews;
drop policy if exists "product_reviews_update_own" on public.product_reviews;
drop policy if exists "product_reviews_delete_own" on public.product_reviews;
create policy "product_reviews_select" on public.product_reviews for select using (approved or (subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "product_reviews_insert" on public.product_reviews for insert to authenticated with check ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "product_reviews_update" on public.product_reviews for update to authenticated using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((subscriber_id = (select auth.uid())) and (not approved)) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "product_reviews_delete" on public.product_reviews for delete to authenticated using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "missing_part_requests_admin_write" on public.missing_part_requests;
drop policy if exists "mpr_insert_own" on public.missing_part_requests;
drop policy if exists "mpr_select_own" on public.missing_part_requests;
create policy "mpr_select" on public.missing_part_requests for select using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "mpr_insert" on public.missing_part_requests for insert with check ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "mpr_admin_update" on public.missing_part_requests for update using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "mpr_admin_delete" on public.missing_part_requests for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "orders_admin_write" on public.orders;
drop policy if exists "orders_insert_own" on public.orders;
drop policy if exists "orders_select_own" on public.orders;
drop policy if exists "orders_update_own" on public.orders;
create policy "orders_select" on public.orders for select using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "orders_insert" on public.orders for insert with check ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "orders_update" on public.orders for update using ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check ((subscriber_id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "orders_admin_delete" on public.orders for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "subscribers_admin_write" on public.subscribers;
drop policy if exists "subscribers_insert_own" on public.subscribers;
drop policy if exists "subscribers_select_own" on public.subscribers;
drop policy if exists "subscribers_update_own" on public.subscribers;
create policy "subscribers_select" on public.subscribers for select using ((id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscribers_insert" on public.subscribers for insert with check ((id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscribers_update" on public.subscribers for update using ((id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin')) with check ((id = (select auth.uid())) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscribers_admin_delete" on public.subscribers for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
drop policy if exists "service role all" on public.subscriber_penalties;
drop policy if exists "subscriber_penalties_admin_write" on public.subscriber_penalties;
drop policy if exists "anon read own" on public.subscriber_penalties;
drop policy if exists "anon update own" on public.subscriber_penalties;
create policy "subscriber_penalties_select" on public.subscriber_penalties for select using (((select auth.email()) = subscriber_email) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscriber_penalties_update" on public.subscriber_penalties for update using (((select auth.email()) = subscriber_email) or ((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscriber_penalties_admin_insert" on public.subscriber_penalties for insert with check (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
create policy "subscriber_penalties_admin_delete" on public.subscriber_penalties for delete using (((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin'));
